checkbox-ng/README.rst
checkbox-ng/checkbox_ng/launcher/startprovider.py
checkbox-ng/requirements/deb-core.txt
checkbox-ng/setup.cfg
checkbox-ng/setup.py
checkbox-support/checkbox_support/scripts/run_watcher.py
checkbox-support/checkbox_support/scripts/tests/test_zapper_proxy.py
checkbox-support/checkbox_support/scripts/zapper_proxy.py
providers/base/bin/edid_cycle.py
providers/base/bin/pm_test.py
providers/base/bin/removable_storage_watcher.py
providers/base/bin/storage_test.py
providers/base/bin/virtualization.py
providers/base/requirements/deb-base.txt
providers/base/requirements/repo-core.txt
providers/base/units/bluetooth/jobs.pxu
providers/base/units/bluetooth/test-plan.pxu
providers/base/units/input/jobs.pxu
providers/base/units/zapper/jobs.pxu
providers/base/units/zapper/test-plan.pxu
providers/certification-client/units/client-cert-desktop-22-04.pxu
providers/certification-client/units/client-cert-odm-desktop-22-04.pxu
providers/certification-client/units/client-cert-odm-server-22-04.pxu
providers/certification-client/units/client-cert-odm-ubuntucore-22.pxu

This PR updates the monorepo with commits that landed on the legacy repos on Launchpad.

Monorepo refresh from LP

---

README.md

Add README.md to clarify the new structure (monorepo).
Fixes Jira issue CHECKBOX-176

Add README.md to explain the content of the Git repository

---

.github/workflows/issues_to_jira.yaml

filter jira sync

---

checkbox-snap/.bumpversion.cfg
checkbox-snap/series_classic16/snap/snapcraft.yaml
checkbox-snap/series_classic18/snap/snapcraft.yaml
checkbox-snap/series_classic20/snap/snapcraft.yaml
checkbox-snap/series_classic22/snap/snapcraft.yaml
checkbox-snap/series_uc16/snap/snapcraft.yaml
checkbox-snap/series_uc18/snap/snapcraft.yaml
checkbox-snap/series_uc20/snap/snapcraft.yaml
checkbox-snap/series_uc22/snap/snapcraft.yaml

checkbox snap version bump (2.4.dev->2.5.dev)

Bump checkbox snaps version: 2.4.dev → 2.5.dev

---

checkbox-ng/docs/side-loading.rst

Documentation update to refresh the ["Side-loading Providers" page.](https://checkbox.readthedocs.io/en/latest/side-loading.html)

Update Checkbox documentation section about side-loading providers

---

providers/base/units/bluetooth/jobs.pxu

> Add manifest to detect the job that supports Bluetooth
N/A

Add manifest to detect the job that supports bluetooth.

---

metabox/README.md

Add README for Metabox

---

providers/base/bin/cpuid.py

- Adding an additional CPUID for Ice Lake in the CPUID script
- Adding an additional CPUID for Ice Lake in the CPUID script

Adding an additional CPUID for Ice Lake in the CPUID script

---

providers/certification-client/units/client-cert-desktop-22-04.pxu
providers/certification-client/units/client-cert-iot-server-22-04.pxu
providers/certification-client/units/client-cert-iot-ubuntucore-22.pxu

Remove [DRAFT] from 22.04 test plans

---

providers/base/units/disk/test-plan.pxu

Removed apste_support_on_.* from Server Certification disk tests
[Note the Jira/Launchpad issue(s) resolved by this PR (`Fixes|Resolves ...`).](https://warthogs.atlassian.net/browse/SERVCERT-455)

Remove APSTE support test for Server Certification

---

providers/base/bin/lid_close_suspend_open.sh
providers/base/units/graphics/test-plan.pxu
providers/base/units/power-management/jobs.pxu

- Add a new semi-auto job "lid_close_open" to combine "lid_close", and "lid_open".
- It will also check if the laptop is suspend when lid close.
None
1. Boot in OS
2. Execute "checkbox-cli run com.canonical.certification::power-management/lid_close_suspend_open" or select in the "manual test plan"
3. Flow the job's step
Slide load on my laptop:
**PASS: when lid close and suspend successful:**
```
------------------[ power-management/lid_close_suspend_open ]-------------------
ID: com.canonical.certification::power-management/lid_close_suspend_open
Category: com.canonical.plainbox::power-management
Purpose:
This test will check your lid sensor can detect lid close/open, and DUT will suspend when the lid closed
Steps:
1. Press "Enter" to start the test
2. Close …
```

Modify: Lid Close, Suspend, Open

---

checkbox-core-snap/.bumpversion.cfg
checkbox-core-snap/series16/snap/snapcraft.yaml
checkbox-core-snap/series18/snap/snapcraft.yaml
checkbox-core-snap/series20/snap/snapcraft.yaml
checkbox-core-snap/series22/snap/snapcraft.yaml

checkbox-core-snap 2.1 release preparation
Bumping to 2.1 to match the deb versioning 
#322 #324

Checkbox core snap parts tags update

---

tools/release/README.md

Update Debian release process README with a few checkups to do along the way.
(Also modified the markdown of existing paragraphs to fit 80 chars)

Update Debian Release README

---

metabox/configs/source-local-config.py
metabox/configs/source-remote-config.py
metabox/metabox/core/actions.py
metabox/metabox/core/aggregator.py
metabox/metabox/core/machine.py
metabox/metabox/core/runner.py
metabox/metabox/core/scenario.py
metabox/metabox/metabox-provider/units/basic-jobs.pxu
metabox/metabox/metabox-provider/units/basic-tps.pxu
metabox/metabox/scenarios/basic/run-invocation.py
metabox/metabox/scenarios/config/config_files/checkbox_etc_xdg.conf
metabox/metabox/scenarios/config/config_files/checkbox_home_dir.conf
metabox/metabox/scenarios/config/config_files/checkbox_snap_dir.conf
metabox/metabox/scenarios/config/launcher.py
metabox/metabox/scenarios/desktop_env/launcher.py
metabox/metabox/scenarios/restart/launcher.py
metabox/metabox/scenarios/urwid/testplan.py

- Add support to send files in Metabox scenarios
- By default, scenarios will be run in every modes (local, remote). This can be overridden per scenario.
- Add initial scenarios to check Checkbox config options and precedence (see individual commits messages for more info)
CHECKBOX-425 (still missing stuff for specific config as well as other parts of the launcher)
1.  Setup Metabox in a venv
2. Adjust `metabox/configs/source-local-config.py` to match the local Checkbox directory on your computer
3. Run:
```
metabox source-local-config.py --log TRACE --tag config --do-not-dispose
```
Output should look like: https://pastebin.ubuntu.com/p/TKScVVHydj/

Metabox: Add initial scenarios to check Checkbox config

---

providers/base/bin/cpuid.py

Add some cpu ids in the cpuid.py script
N/A

Add some more CPUID in the cpuid.py script

---

.github/workflows/metabox.yaml
metabox/configs/local-source-16.04.py
metabox/configs/local-source-18.04.py
metabox/configs/local-source-20.04.py
metabox/configs/local-source-22.04.py
metabox/configs/remote-source-16.04.py
metabox/configs/remote-source-18.04.py
metabox/configs/remote-source-20.04.py
metabox/configs/remote-source-22.04.py
metabox/metabox/core/configuration.py
metabox/metabox/core/machine.py
metabox/setup.py

Create a GitHub action to run Metabox on a variety of configs (Checkbox local, remote, Ubuntu 18.04/20.04/22.04) when a PR is approved.
CHECKBOX-451

Integrate Metabox in the Github workflow

---

.github/workflows/checkbox-core-snap-daily-builds.yml
.github/workflows/checkbox-snap-daily-builds.yml

Follow up to https://github.com/canonical/checkbox/pull/392

Add git short sha suffix to daily builds uploaded to the edge channel

---

checkbox-ng/plainbox/impl/exporter/jinja2.py

Checkbox Jinja2 exporter compatibility with Jinja2 3.1 ([Lunar packaged version](https://packages.ubuntu.com/lunar/python3-jinja2))
Lunar FTBFS

Fix: Jinja2 3.1 compatibility (Lunar packaged version)

---

checkbox-ng/debian/control
checkbox-ng/setup.py

Add missing dependency on python3-packaging
Bionic FTBFS

Fix: Add new python3-packaging dependency

---

providers/docker/units/docker.pxu

Fix docker test whitespace, services and version are top level keys

---

.github/workflows/checkbox-stable-release.yml
tools/release/lp-copy-packages.py

Stable release workflow

---

tools/release/README.md

New workflows are now available to release checkbox using a unique tag.
This is the documentation update corresponding to: 
- https://github.com/canonical/checkbox/pull/402
- https://github.com/canonical/checkbox/pull/408

Update the release README

---

checkbox-core-snap/series16/snap/snapcraft.yaml
checkbox-core-snap/series18/snap/snapcraft.yaml
checkbox-core-snap/series20/snap/snapcraft.yaml
checkbox-core-snap/series22/snap/snapcraft.yaml

Update stress-ng part to v0.15.07 in checkbox-core-snap

---

checkbox-ng/docs/custom-app.rst
checkbox-ng/docs/launcher-tutorial.rst

Small documentation fixes.
Check commit messages for more info.

Fix docs (launchers tutorial, sphinx warning)

---

.github/workflows/metabox.yaml

The workflow does not seem to be triggered even when it should be.
Adding some debugging info to try to figure out what's wrong.

Add debugging info to the Metabox Github Action

---

checkbox-ng/plainbox/impl/unit/test_testplan.py

Minor fix for wrong usage of unit type in a test

---

providers/base/bin/graphics_env.sh

This is caused by some timing issue in the suspend/resume process.
In some very rare cases, `XDG_SESSION_TYPE` is not set, which causes `[ "$XDG_SESSION_TYPE" == "wayland" ]` to make the wrong decision.
Keep polling the value of `XDGSESSION_TYPE` from `systemctl --user show-environment`.
Fix this issue: #59
ThinkPad P series, Okay.

Fix XDG_SESSION_TYPE is not set.

---

metabox/metabox/core/lxd_provider.py

This fixes the crash when metabox is started with a `metabox*` containers already running. Metabox crashes because it is unable to categorize the container but if it has to be used, it tries to recreate it, crashing wih `Failed creating instance record: Add instance info to the database: This "instances" entry already exists`
This also fixes the issue if the already started container is half baked by catching NotFound (config file) and deleting the old container, allowing the recreation to take place
N/A
N/A
This was tested by running metabox on a running container, an half baked one and a stopped one.

Fix metabox crash on already started containers

---

docs/reference/units/template.rst

Minor improvements of the template unit documentation

---

.github/workflows/metabox.yaml
metabox/metabox/core/configuration.py
metabox/metabox/core/machine.py

Metabox can not run in github actions because it fails to dry install checkbox-ng. This fixes this problem
N/A
N/A
N/A

Fix Metabox fails to run in github action

---

checkbox-ng/plainbox/impl/__init__.py
checkbox-ng/plainbox/impl/clitools.py
checkbox-ng/plainbox/impl/commands/__init__.py
checkbox-ng/plainbox/impl/providers/__init__.py
checkbox-ng/plainbox/impl/resource.py
checkbox-ng/plainbox/impl/session/jobs.py
providers/base/bin/frequency_governors_test.py

typos: fix a number of typos in comments; no functional change

---

checkbox-core-snap/series16/snap/snapcraft.yaml
checkbox-core-snap/series18/snap/snapcraft.yaml
checkbox-core-snap/series20/snap/snapcraft.yaml
checkbox-core-snap/series22/snap/snapcraft.yaml

This updates the fwts version to the latest
Resolves: https://warthogs.atlassian.net/browse/CHECKBOX-770
N/A
Succesfully built via remote-build on series16, 18, 20 and 22

Updated fwts tag

---

CONTRIBUTING.md

Add a section on how to contribute to documentation in the contributing guide.
CHECKBOX-848
Tested using the steps described in this commit :)

Add documentation section in the contributing guide (infra)

---

checkbox-core-snap/series16/snap/snapcraft.yaml
checkbox-core-snap/series18/snap/snapcraft.yaml
checkbox-core-snap/series20/snap/snapcraft.yaml
checkbox-core-snap/series22/snap/snapcraft.yaml

This upgrades fwts to the latest version
N/A
N/A
Every runtime snap was built via remote builds and it finished building correctly

Upgrade fwts version in runtime snaps (New)

---

providers/base/bin/recovery_info.py

Fixed a small typo in recovery_info.py
"partiion" -> "partition"

fix a typo in recovery_info.py (BugFix)

---

.github/workflows/checkbox-core-snap-beta-release.yml
.github/workflows/checkbox-core-snap-daily-builds.yml
.github/workflows/checkbox-snap-beta-release.yml
.github/workflows/checkbox-snap-daily-builds.yml

Snapcraft remote-builds upload the logs in the `series` directory. We need these logs because they contain the failure reason  else we have to re-build the snap to see what failed.
Resolves: https://warthogs.atlassian.net/browse/CHECKBOX-948
N/A
N/A

Upload all checkboxXX_arch.txt logs (infra)

---

providers/base/bin/audio_driver_info.py

Dummy commit to get a version greater than 2.49 to upload daily debs builds to the dev ppa (e.g `2.10.2.dev50+gb6b298899`)
https://code.launchpad.net/~checkbox-dev/+archive/ubuntu/ppa/+recipebuild/3622540
N/A
N/A

Add missing header to audio_driver_info.py (New)

---

.github/workflows/checkbox-core-snap-daily-builds.yml
.github/workflows/checkbox-snap-daily-builds.yml
.github/workflows/daily-builds.yml
.github/workflows/deb-daily-builds.yml

Moves the daily builds to 18 UTC, in the daily-builds.yml workflow

Moves the daily builds to 18 UTC (Infra)

---

.github/workflows/checkbox-core-snap-beta-release.yml
.github/workflows/checkbox-core-snap-daily-builds.yml
.github/workflows/checkbox-snap-beta-release.yml
.github/workflows/checkbox-snap-daily-builds.yml
.github/workflows/deb-beta-release.yml
.github/workflows/deb-daily-builds.yml

We have upgraded the daily build workflow significantly in these days, including separated builds, retries and new descriptions. This PR ports these improvements over to the beta workflow.
N/A
N/A
N/A

Sync beta edge workflow (infra)

---

.github/pull_request_template.md
CONTRIBUTING.md

Explain the signed commit requirement in documentation…
- in the contribution guide
- in the PR template

Note the signed commit requirement (Infra)

---

.github/.jira_sync_config.yaml

Establishing and initial gh to jira sync config
Config for the gh jira sync bot

Create .jira_sync_config.yaml (Infra)

---

providers/base/tests/test_camera_quality.py
providers/base/tests/test_camera_test.py
providers/base/tests/test_dkms_info.py
providers/base/tests/test_recovery_info.py

Replaced print and log functions for mocks for the tests in the base provider.
Some of the prints and logs appeared in the output when running the tests. This commit mocks all the print/log functions used in the base provider tests.
`./manage.py test -u` no longer shows the output of print/log functions.

Mocked print and log functions for tests (Infra)

---

checkbox-core-snap/README.md

Small typo on the documentation of checkbox-core-snap

lxc instead of lxd in checkbox-core-snap readme (Infra)

---

.github/workflows/deb-beta-release.yml

We need the history to calculate the version. This is the fix from the last beta release

Fixed missing history in deb builds (infra)

---

checkbox-support/checkbox_support/parsers/udevadm.py

filter Intel IPU6 video driver in udevadm
Intel image process unit 6th generation (IPU6) needs userspace library to make it funcional. It is not able to control direclty with V4L2 api. Filter those device out from udevadm to make camera test works corretly.
Fixes #848

Add: filter Intel IPU6 video driver in udevadm (BugFix)

---

checkbox-support/checkbox_support/tests/test_vendor_beacontools_scanner.py
checkbox-support/checkbox_support/vendor/beacontools/scanner.py

The BT 5.4 is out and DUTs is starting to test this spec.
Therefore, following the [previous one](https://github.com/canonical/checkbox/commit/f53f59ac5769dfb4df406715388bc47fcb6da2b0) to add this spec into support list.
#834 
[non-modified submission](https://certification.canonical.com/hardware/202310-32266/submission/343109/test-results/fail/)
[modified submission](https://certification.canonical.com/hardware/202310-32266/submission/344688/test-results/pass/)

Add BT_CORE_SPEC_5_4 = 13 to HCIVersion Enum (BugFix)

---

providers/tpm2/bin/tpm2_capabilities.py

This PR is simply to add non zero return value to make checkbox could know this test is failed.
If I would like to add unit test for this, the only way I know is to refactor whole script and I think we have arrangement that refractory old codes is not what QA team have to do.
#789

Fix `tpm2_capabilities.py` always return success while no tpm tool or chip installed (Bugfix)

---

CONTRIBUTING.md

- Provide clearer information on how to run tests for providers (unit tests especially)
- Provide more information about test coverage, including how to generate an HTML report
- Reword some sections to help potential contributors to get started
- Cleaned up some markup to make the whole doc more consistent
See individual commits for more info.
Checked generated HTML looked OK in GitHub.

Update contributing guide (infra)

---

providers/certification-client/units/client-cert-desktop-24-04.pxu
providers/certification-client/units/client-cert-iot-server-24-04.pxu
providers/certification-client/units/client-cert-iot-ubuntucore-24.pxu
providers/certification-client/units/client-cert-odm-desktop-24-04.pxu
providers/certification-client/units/client-cert-odm-server-24-04.pxu
providers/certification-client/units/client-cert-odm-ubuntucore-24.pxu

Copy of the 22.04 and uc22 tests plans to create draft for 24.04/UC24
`manage.py validate`

Ubuntu 24.04 & Core 24 test plans (New)

---

.github/pull_request_template.md

There's typo in `pull_request_template.md`.
Change from `chage` to `change`.
N/A
N/A
N/A

Fix typo in pull_request_template.md (infra)

---

.vscode/settings.json
CONTRIBUTING.md

Adds code review guidelines into the contribution guide.

Code review guidelines (Infra)

---

providers/base/bin/check-ubuntu-desktop-recommends.sh

This PR is the rebased version of the following PR: 
https://github.com/canonical/checkbox/pull/640
It might be quicker to land it with this PR than go chasing rebases with the original one.

Check the installed package instead of from ubuntu-archive (bugfix)

---

providers/base/units/power-management/jobs.pxu

Updated the documentation link for s0ix troubleshooting guide.
Original links were broken and alternative links were suggested by Intel.
Closes #906

Update the document link for s0ix troubleshooting guide. (infra) (#906)

---

providers/base/units/fingerprint/jobs.pxu

$ sudo env | grep SUDO
SUDO_COMMAND=/usr/bin/env
SUDO_USER=ubuntu
SUDO_UID=1001
SUDO_GID=1001
when running checkbox with sudo, it will 'fprintd-enroll 1001' and the test case will lock screen to let 'ubuntu' user to login, but at that time, it will not work because the user is not 'ubuntu'.

fprintd should enroll a user, not a uid (BugFix)

---

CONTRIBUTING.md

Modified the English of the code review section for readability, but no intent to change meaning.
None, opinion on documentation only.
n/a
N/a

Update CONTRIBUTING.md (Infra)

---

.github/workflows/checkbox-beta-release.yml

Before the steps, the github workflow grammar requires a `steps:` keyword. This adds it fixing the workflow
Workflow is broken
N/A
N/A

Added missing `steps:` to pipeline (infra)

---

contrib/checkbox-provider-ce-oem/README.md
contrib/checkbox-provider-ce-oem/units/crypto/crypto_generic.pxu

Since the ce-oem provider namespace was switched to `com.canonical.contrib`, some jobs need to be updated, otherwise the provider validation fails.
CHECKBOX-1157
Locally, in a venv with Checkbox installed:
```
$ ./manage.py develop -d $PROVIDERPATH
$ ./manage.py validate
(...)
The provider seems to be valid
```

Fix namespace for ce-oem jobs (Infra)

---

checkbox-support/checkbox_support/parsers/udevadm.py

This is a fix for LP:#2051091. 
For the usb camera '5986:118c Acer, Inc Integrated Camera, it will be put into the category "CARDREADER", and all the camera tests will be ignored. 
The device lists could be found here: https://certification.canonical.com/devices/108163
https://bugs.launchpad.net/sutton/+bug/2051091
NA
https://certification.canonical.com/hardware/202309-32040/submission/353502/test-results/

Fix the wrong category issue for the camera 5986:118c (BugFix) 

---

providers/base/bin/gateway_ping_test.py
providers/base/tests/test_gateway_ping_test.py

If the ping test fails, it will produce a traceback, this is wrong. This PR changes that leading to a correct failure path
Fixes: https://github.com/canonical/checkbox/issues/494
N/A
Tests added to a new file with 100% coverage of relevant code

Update ping test to not crash on failing pings (BugFix)

---

providers/certification-server/configs/canonical-certification.conf
providers/certification-server/tools/canonical-certification-precheck

Updated the canonical-certification.conf for noble
Updated the precheck script to remove the UVT_KVM test 
Updated the script to call the KVM check image test
In anticipation for updating the configuration files  virtualization test for 24.04, simple changes were needed in the configuration file and the precheck script.

Update the Virtualization Script for 24.04 (BugFix)

---

metabox/metabox/core/lxd_execute.py
metabox/metabox/core/scenario.py
metabox/metabox/core/utils.py

This fixes the expect function to support all use cases and turns the stdout_data buffer into a string instead of always encoding every search pattern, decoding the message data.
Broken main metabox
N/A
N/A

Fix metabox expect typerror (infra)

---

checkbox-core-snap/common_files/config/wrapper_common
checkbox-core-snap/common_files/config/wrapper_common_classic
checkbox-core-snap/series22/snap/snapcraft.yaml

To run the camera quality tests, we included installing the "python3-opencv" library, which included many features that we were not using, thus increasing noticeably the size of the snap. 
This change modifies the series22 snap to include a version of openCV built from source only with the necessary packages, keeping the snap size as low as possible. This leads to a reduction of ~70MB on the total snap size
Resolves [CHECKBOX-949](https://warthogs.atlassian.net/browse/CHECKBOX-949)
No additions to the documentation
To test that the change is successful, build the snap and run the camera quality tests on a device that has a webcam.
[CHECKBOX-949]: https://warthogs.atlassian.net/browse/CHECKBOX-949?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Opencv build from source on snaps (New)

---

checkbox-core-snap/series22/snap/snapcraft.yaml

This change is not needed anymore since we are building opencv from source
No documentation changes
Tested using `snapcraft remote-build --build-on amd64,arm64,armhf`
Review tools passed:
```
$ review-tools.snap-review ./checkbox22_4.0.0-dev126_armhf.snap
./checkbox22_4.0.0-dev126_armhf.snap: pass
```

Revert  libde265 change on armhf (Bugfix)

---

.github/workflows/tox-tools-release.yaml
.github/workflows/validate_workflows.yaml

2 workflows were edited yesterday, but fail yaml validation because of a misaligned field (and as a result, spit out erros when the workflows are executed). This PR fixes this.

Fix errors in GitHub workflow yaml files (infra)

---

checkbox-ng/checkbox_ng/launcher/controller.py

Peeking an unfinished session via resume -> throw away introduced a bug that will crash checkbox if the latest session is incompatible. We tried to fix this by catching the exception that is produced but rpyc changes the type of the remote exception. This PR catches and re-creates the exception back to the original type
Minor: this removes a pointless call to abandon_session
N/A
This adds a new comment explaining why this is done
N/A

Cast back exception to local type (bugfix)

---

providers/base/units/wireless/jobs.pxu

Commit da9c843 mistakenly removed this job.

Re-introduce wireless/check_iwlwifi_microcode_crash_{interface} template (BugFix)

---

providers/base/tests/test_storage_test.py
providers/base/tox.ini

When working on the #1003 I thought I will have to modify the `storage_test.py`, so when I started reading it, I wrote some tests along the way.
Turns out I didn't have to modify the file, but the tests are still valuable, so let's have them :)
are being proposed here...

Add tiny bit of tests to the storage tests (New)

---

contrib/checkbox-provider-ce-oem/units/strict-confinement/test-plan-strict-confinement.pxu
contrib/checkbox-provider-ce-oem/units/strict-confinement/thermal-strict-confinement.pxu

Add a thermal sensor test in strict confinement mode. We leverage the [existing test](https://github.com/canonical/checkbox/blob/main/contrib/checkbox-provider-ce-oem/units/thermal-sensor/jobs.pxu#L9). However, we are not able to call stress-ng in strict confinement mode. Therefore, we calling the "dd" command here to try to increase system loading.
This test case relies on [test-strict-confinement](https://code.launchpad.net/~oem-qa/+git/test-strict-confinement/+ref/master) SNAP
N/A
Sideload result:
https://certification.canonical.com/hardware/202304-31485/submission/360642/test-results/

[checkbox-ce-oem] Add thermal test in strict confinement mode(New)

---

contrib/checkbox-provider-ce-oem/bin/look_up_xtest.py
contrib/checkbox-provider-ce-oem/bin/parse_optee_test.py
contrib/checkbox-provider-ce-oem/units/optee/jobs.pxu

Modify the job and script to support running the [x-test](https://github.com/canonical/x-test-snap) snap. The x-test snap is a snap that executes the OPTEE test. We intend to allow users to test OPTEE either via the xtest included in the gadget snap or the xtest included in the x-test snap.
N/A
N/A
Sideload results with the xtest that is included in gadget snap:
https://pastebin.canonical.com/p/HPbYZtVyrs/
Sideload results with the xtest that is included in x-test snap:
https://certification.canonical.com/hardware/202401-33430/submission/360530/
Sideload results with no xtest found in the system:
https://certification.canonical.com/hardware/202401-33430/submission/360527/

[Checkbox-ce-oem] Modify job and script to support use x-test tool(Bugfix)

---

docs/reference/units/template.rst

Following a discussion with QA, add an example of a `template-summary` field in the Template Unit reference page.

Add example to the Template unit template-summary field (Infra)

---

providers/resource/bin/snapd_resource.py
providers/resource/tests/test_snapd_resource.py

`snapd_resource.Features` class is designed for Ubuntu Core only, but some jobs might call it from a classic version of Ubuntu.
Refactor the `snapd_resource.Features` class to:
- have a method (`_has_kernel_extraction_feature`) that returns True or False depending on the previously used criteria and the fact that Ubuntu Core is being used
- modify the `invoked` section to do the printing, resulting in easier testing
Fix #963

Refactor snapd_resource.Features methods (BugFix)

---

checkbox-ng/plainbox/impl/providers/exporters/data/checkbox.json

Now that instantiated jobs contain their template id, we can add this information to the `submission.json` included in each submission archives.
`template_id` field is added for both "results" and "attachment-results" sections, as both may have jobs instantiated from templates, but not for "resource-results" as a resource job should not be generated from another resource job...
Created a small test plan including a normal `shell` job and a templated `attachment` job that outputs two instantiated jobs. Ran this through `checkbox-cli`, and got the following `submission.json` once the run was finished (check for `template_id` fields):
```json
{
"title": "session title",
"testplan_id": "com.canonical.certification::demo-nested1",
"custom_joblist": false,
"results": [
{
"id": "demo-job1", …
```

Update checkbox.json to include template_id (New)

---

providers/genio/bin/boot_partition.py
providers/genio/bin/brightness_test.py
providers/genio/bin/cpu_idle.py
providers/genio/bin/dvfs_gpu_check_governors.py
providers/genio/bin/gpio_loopback_test.py
providers/genio/bin/hdmirx_output_checker.sh
providers/genio/bin/hdmirx_tool_runner.sh
providers/genio/bin/linux_ccf.py
providers/genio/bin/pmic_regulator.py
providers/genio/bin/serialcheck.py
providers/genio/bin/set_as_performance_mode.sh
providers/genio/bin/spidev_test.py
providers/genio/bin/verify-mt8188-ccf.sh
providers/genio/bin/verify-mt8195-ccf.sh

All scripts (python and bash) under the genio provider have now a copyright and license notice
The original author/s have been preserved
https://warthogs.atlassian.net/browse/CHECKBOX-993
N/A
N/A

Added copyright and license notice for scripts in genio provider (Infra)

---

checkbox-support/pyproject.toml

```
$ checkbox-cli run com.canonical.certification::connections
==============[ Running job 1 / 1. Estimated time left: 0:00:01 ]===============
-------------------[ Collect information about connections ]--------------------
ID: com.canonical.certification::connections
Category: com.canonical.certification::information_gathering
File "/tmp/nest-hb2117fq.192267fd7db6d739bf287b9c356cf937eeb1e4c54befcea50064bd0d2ad11985/snapd_resource.py", line 13, in <module>
from checkbox_support.snap_utils.asserts import decode
File "/home/ubuntu/.pyenv/versions/checkbox/lib/python3.10/site-packages/checkbox_sup …
```

checkbox-support: add missing `pyyaml` dependency (BugFix)

---

providers/base/units/suspend/suspend.pxu

change `deamon` to `daemon` to make the naming match to the script filename
#1117
[submission](https://certification.canonical.com/hardware/202401-33397/submission/362311/test-results/pass/)

change the naming of `check_audio_deamon.sh` to `check_audio_daemon.sh` (BugFix)

---

contrib/checkbox-provider-ce-oem/series_classic20/config/config_vars
contrib/checkbox-provider-ce-oem/series_classic20/launchers/checkbox-cli-wrapper
contrib/checkbox-provider-ce-oem/series_classic20/launchers/configure
contrib/checkbox-provider-ce-oem/series_classic20/launchers/shell-wrapper
contrib/checkbox-provider-ce-oem/series_classic20/launchers/test-runner
contrib/checkbox-provider-ce-oem/series_classic20/launchers/wrapper_local
contrib/checkbox-provider-ce-oem/series_classic20/snap/hooks/configure
contrib/checkbox-provider-ce-oem/series_classic20/snap/hooks/install
contrib/checkbox-provider-ce-oem/series_classic20/snap/snapcraft.yaml
contrib/checkbox-provider-ce-oem/series_classic22/config/config_vars
contrib/checkbox-provider-ce-oem/series_classic22/launchers/checkbox-cli-wrapper
contrib/checkbox-provider-ce-oem/series_classic22/launchers/configure
contrib/checkbox-provider-ce-oem/series_classic22/launchers/shell-wrapper
contrib/checkbox-provider-ce-oem/series_classic22/launchers/test-runner
contrib/checkbox-provider-ce-oem/series_classic22/launchers/wrapper_local
contrib/checkbox-provider-ce-oem/series_classic22/snap/hooks/configure
contrib/checkbox-provider-ce-oem/series_classic22/snap/hooks/install
contrib/checkbox-provider-ce-oem/series_classic22/snap/snapcraft.yaml
contrib/checkbox-provider-ce-oem/series_uc20/snap/snapcraft.yaml
contrib/checkbox-provider-ce-oem/series_uc22/config/config_vars
contrib/checkbox-provider-ce-oem/series_uc22/launchers/checkbox-cli-wrapper
contrib/checkbox-provider-ce-oem/series_uc22/launchers/configure
contrib/checkbox-provider-ce-oem/series_uc22/launchers/shell-wrapper
contrib/checkbox-provider-ce-oem/series_uc22/launchers/test-runner
contrib/checkbox-provider-ce-oem/series_uc22/launchers/wrapper_local
contrib/checkbox-provider-ce-oem/series_uc22/snap/hooks/configure
contrib/checkbox-provider-ce-oem/series_uc22/snap/hooks/install
contrib/checkbox-provider-ce-oem/series_uc22/snap/snapcraft.yaml

There were snapcraft.yaml files hosted on LP Git for checkbox-ce-oem to be built and published by LP build infra, as of now checkbox-provider-ce-oem has been hosted in the contrib area of monorepo we should also host snapcraft.yaml files on GH so checkbox-ce-oem snap can be built through GH workflow
Note: This PR only moves snapcraft.yaml files into GH, there hasn't been any changes with regard to building latest checkbox-ce-oem source from contrib area
https://warthogs.atlassian.net/browse/OEMQA-4135

Move checkbox-ce-oem snapcraft.yaml into contrib area (New)

---

providers/base/bin/camera_quality_test.py
providers/base/tests/test_camera_quality.py
providers/base/units/camera/jobs.pxu
providers/base/units/camera/test-plan.pxu

The test camera/camera-quality_.* fails from time to time. Since this test uses an algorithm to determine the output, it can be difficult to assess whether there is really a problem with the webcam or not, especially when reviewing submissions that do not have a sample of the image used for this.
We have added an attachment job to include the image used to compute the quality score so we can check it later.
https://warthogs.atlassian.net/browse/CHECKBOX-1281
Run the camera automated tests:
```
com.canonical.certification::camera-cert-automated
```
Check that the image has been created in the `PLAINBOX_SESSION_SHARE` directory

Add submision for camera quality test (New)

---

.github/workflows/checkbox-beta-release.yml
.github/workflows/checkbox-core-snap-beta-release.yml
.github/workflows/checkbox-core-snap-daily-builds.yml
.github/workflows/checkbox-snap-beta-release.yml
.github/workflows/checkbox-snap-daily-builds.yml
.github/workflows/checkbox-stable-release.yml
.github/workflows/daily-builds.yml
.github/workflows/deb-beta-release.yml
.github/workflows/deb-daily-builds.yml
.github/workflows/documentation-build-readthedocs.io.yml
.github/workflows/documentation-check.yml
.github/workflows/pr_validation.yaml
.github/workflows/release-notes.yml

Update workflows to specify series tag.

Update workflows to specify series (Infra)

---

providers/base/units/submission/test-plan.pxu
providers/certification-server/units/firmware-tests.pxu

BugFix: Add explicit blocker/non-blocker status to a few tests
Jeff wanted these set explicitly, so this merge does so.
https://warthogs.atlassian.net/browse/SERVCERT-1514
These changes should be picked up automatically by scripts/generate_test_guide.py in the certification-docs project, once merged.

blocker/non-blocker status added to a few tests (Bugfix)

---

providers/base/bin/pipewire_utils.py
providers/base/tests/test_pipewire_test.py
providers/base/tests/test_pipewire_utils.py

The device id in the output of `wpctl status` will be changed after suspend since kernel 6.5.0.26 with dGPU installed  .
Therefore, changing shell script to python to make the parsing easier and more robust.  
Test cases change will be addressed in other PR.
as described in the [card](https://warthogs.atlassian.net/browse/CHECKBOX-1282)
Unit test

Fix the audio_after_suspend test failing on mantic (BugFix)

---

.github/workflows/checkbox-ce-oem-edge-builds.yml

Fix the trigger path.
N/A
N/A
N/A

[checkbox-ce-oem] Fix path for checkbox-ce-oem workflow (Bugfix)

---

providers/base/units/graphics/jobs.pxu
providers/base/units/graphics/test-plan.pxu
providers/base/units/monitor/test-plan.pxu
providers/base/units/suspend/suspend.pxu
providers/certification-client/units/client-cert-desktop-24-04.pxu
providers/certification-client/units/client-cert-odm-desktop-24-04.pxu

This is part of #586 that includes the changes of job and test plan only.
1. New jobs that uses prime_offload_tester.py to valid GPU rendering.
2. New test plans that conbimes integrated and discrete GPU into one.
3. Remove unnecessary jobs and test plans after switching to new graphic test strategy.
This PR depends on #586.
if #586 isn't merged yet, please don't merge this one.

Change to new graphic test strategy - jobs and test plans (BugFix)

---

providers/base/units/suspend/suspend.pxu

This PR is part of #1142 that uses the new python script from #1142 to make the test cases could verify status correctly.
as described in the [card](https://warthogs.atlassian.net/browse/CHECKBOX-1282)
- Mantic:
- match: https://certification.canonical.com/hardware/202001-27667/submission/363410/
- not match: https://certification.canonical.com/hardware/202001-27667/submission/363411/
- Jammy:
- match: https://certification.canonical.com/hardware/202401-33398/submission/363413/
- not match:  https://certification.canonical.com/hardware/202401-33398/submission/363414/

Fix the audio_after_suspend test failing on mantic - `test case` (BugFix)

---

.git-blame-ignore-revs
CONTRIBUTING.md

- .git-blame-ignore-revs prevents git blame from showing the black formatting commit
- add suggestion to use black from PyPI instead of version from the Ubuntu repo because the PyPI version is the one used in our CI/CD and repo versions are usually older

Add .git-blame-ignore-revs and update contrib guide (infra)

---

checkbox-support/checkbox_support/parsers/tests/test_udevadm.py
checkbox-support/checkbox_support/parsers/udevadm.py
providers/base/bin/get_firmware_info_fwupd.py
providers/base/tests/test_get_firmware_info_fwupd.py

Some files have not been formatted and were part of PRs that have landed after the black formatting one while not submitted to the black automated check. Fixing this.
Command used:
black  --line-length 79 --extend-exclude '/vendor/' .

More black formatting (infra)

---

.github/workflows/checkbox-ce-oem-daily-build.yml
.github/workflows/checkbox-ce-oem-edge-builds.yml

Build checkbox-ce-oem from when there is new commeit to daily
N/A
N/A
N/A

[checkbox-ce-oem] Add checkbox-ce-oem daily build (Infra)

---

docs/tutorial/using-checkbox/launcher.rst

Fix spelling mistake in tutorial (Bugfix)

---

docs/.sphinx/wordslist.txt
docs/how-to/freeze-checkbox-version.rst
docs/how-to/index.rst

Since we lack a candidate channel presently, and since we have established that there is a Checkbox user segment who is best advised to make very conscious upgrade choices, we have created this documentation on how to freeze the version of Checkbox. 
https://warthogs.atlassian.net/browse/CHECKBOX-1308
Added documentation on how to freeze checkbox.
The checkbox snapshots have been tested for several Ubuntu versions and all the different PPAs.

Documentation on how to freeze checkbox (Infra)

---

providers/base/units/bluetooth/test-plan.pxu

Since [PR#1172](https://github.com/canonical/checkbox/pull/1172) has been merged, Ubuntu Core is able to run obex test now

Include obex test into bluez-automated test plan (New)

---

providers/base/units/miscellanea/test-plan.pxu
providers/base/units/stress/test-plan.pxu
providers/certification-client/units/client-cert-iot-desktop-24-04.pxu
providers/certification-client/units/client-cert-iot-server-24-04.pxu
providers/certification-client/units/client-cert-iot-ubuntucore-24.pxu

- [OQ012 - IoT Checkbox Certification Test Plans for 24.04](https://docs.google.com/document/d/19sXrqIR6PkGtR6TAV_avf2Jt8YqE3Pi4DRWZtMb5Jnw/edit?usp=sharing)
- [OEMQA-4157 Improve the scope and update the IoT Certify Test Plans](https://warthogs.atlassian.net/browse/OEMQA-4157)

Improve the 24.04 IoT Cert Test Plans (New)

---

.github/workflows/core24-builds.yml
checkbox-snap/series_classic24/snap/snapcraft.yaml
checkbox-snap/series_uc24/snap/snapcraft.yaml

Snapcraft 8 seems to choke on the legacy command. This replaces it with the new one

Bump snapcraft version core24 (infra)

---

CONTRIBUTING.md

Add a session to teach user how to build executables under src/ under each provider.
N/A
N/A
N/A

Add the session for building executables in CONTRIBUTE.md (Infra)

---

providers/base/units/graphics/jobs.pxu

This is part of #1247 and use the script that merged in it to make sure
the result is correct and remove the color code at the same time.
#1122
https://certification.canonical.com/hardware/202001-27667/submission/372182/

Fix id: graphics/{index}_gl_support_{product_slug} alway return ture (BugFix)

---

contrib/pc-sanity/bin/platform_meta_test
contrib/pc-sanity/bin/screen-pkg.py
contrib/pc-sanity/units/pc-sanity/pc-sanity.pxu

pick 3 patches from old pc-sanity repo
484e06d8: make miscellanea/check-gpu-driver a cert-blocker
8088828c: Drop lsb_release for 24.04. (NANTOU-343)
4f81f9e8: platform_meta_test: include noble

Pick patch from old pc-sanity repo (Bugfix)

---

contrib/pc-sanity/debian/rules

Correct the manage.py root directory

Fix the pc-sanity install path (BugFix)

---

contrib/pc-sanity/debian/rules

Fix the compiled c binary file install path

Fix the c binary install path in pc-sanity (Bugfix)

---

providers/base/units/graphics/jobs.pxu

Add `environ` to prevent from issue #1101 
N/A
N/A
N/A

Add environ field (Bugfix)

---

providers/certification-client/units/client-cert-odm-server-22-04.pxu
providers/certification-client/units/client-cert-odm-server-24-04.pxu
providers/certification-client/units/client-cert-odm-ubuntucore-22.pxu
providers/certification-client/units/client-cert-odm-ubuntucore-24.pxu

Add new placeholder test plans to `client-cert-odm-server` and `client-cert-odm-ubuntucore` pxus to provide a single entry for both automated and manual test plans in 22.04 and 24.04. 
The new entries are only used for generating test coverage documentation and do not impact existing tests.
Such placeholder already exists in [`odm-desktop`](https://github.com/canonical/checkbox/blob/main/providers/certification-client/units/client-cert-odm-desktop-24-04.pxu#L199) and other iot test plans. 
[CHECKBOX-1227](https://warthogs.atlassian.net/browse/CHECKBOX-1227)
N/A
N/A
[CHECKBOX-1227]: https://warthogs.atlassian.net/browse/CHECKBOX-1227?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add placeholder test plans as single entry for ODM cert coverage guide (Infra)

---

contrib/pc-sanity/debian/rules

In Noble, the oscap command comes from package openscap-scanner, depends on it as well.

plainbox-provider-pc-sanity (noble): depends openscap-scanner as well (BugFix)

---

contrib/checkbox-ce-oem/checkbox-ce-oem-snap/series_classic20/snap/snapcraft.yaml
contrib/checkbox-ce-oem/checkbox-ce-oem-snap/series_classic22/snap/snapcraft.yaml
contrib/checkbox-ce-oem/checkbox-ce-oem-snap/series_classic24/snap/snapcraft.yaml
contrib/checkbox-ce-oem/checkbox-ce-oem-snap/series_uc20/snap/snapcraft.yaml
contrib/checkbox-ce-oem/checkbox-ce-oem-snap/series_uc22/snap/snapcraft.yaml
contrib/checkbox-ce-oem/checkbox-ce-oem-snap/series_uc24/snap/snapcraft.yaml
contrib/checkbox-ce-oem/checkbox-provider-ce-oem/bin/spidev_test.py
contrib/checkbox-ce-oem/checkbox-provider-ce-oem/units/spi/category.pxu
contrib/checkbox-ce-oem/checkbox-provider-ce-oem/units/spi/jobs.pxu
contrib/checkbox-ce-oem/checkbox-provider-ce-oem/units/spi/manifest.pxu
contrib/checkbox-ce-oem/checkbox-provider-ce-oem/units/spi/resource.pxu
contrib/checkbox-ce-oem/checkbox-provider-ce-oem/units/spi/testplan.pxu
contrib/checkbox-ce-oem/checkbox-provider-ce-oem/units/test-plan-ce-oem.pxu

Add SPI Test. Originally from [checkbox-provider-baoshan](https://git.launchpad.net/~baoshan-team/baoshan/+git/checkbox-provider-baoshan/tree/units/peripheral/jobs.pxu#n46)
N/A
N/A
https://certification.canonical.com/hardware/202405-34024/submission/375779/

[checkbox-ce-oem] Add SPI Test (New)

---

providers/base/units/optical/jobs.pxu
providers/base/units/optical/manifest.pxu
providers/base/units/optical/test-plan.pxu

This PR was used to automated the DVD test, which used to be a manual test. After the change, the manual tests will be removed from the manual test plan, and a DVD read test will be added to the automatic test plan. 
If the DUT with a DVD or Bluray device, before run the automatic test, a new manifest item "has_dvd_bluray_inserted" will be asked. If the has_dvd_bluray_inserted had been labeled as yes, and a DVD or bluray disc was insterted. The DVD/Bluray read test will be run in the Automatic test.
* Remove DVD test from the Manual test plan
* Add a DVD read test to Automatic test plan
* Add a manifest has_dvd_bluray_inserted
Please refter the https://warthogs.atlassian.net/browse/OEMQA-4085 for more info and the test results.

Automate DVD test (New)

---

contrib/checkbox-ce-oem/checkbox-provider-ce-oem/units/gpio/jobs.pxu

To prevent the issue of get empty manifest in very first run of checkbox test
A resource job that require manifest will cause menifest becom empty in the very first run of checkbox test. 
e.g. The checkbox test run right after system installed.

[checkbox-ce-oem] Remove manifest from resource job (BugFix)

---

providers/base/units/audio/jobs.pxu

Following internal discussion, add more info about the purpose of the audio/alsa_record_playback_automated and audio/alsa-loopback-automated jobs.
audio/alsa_record_playback_automated was created as a mean to test laptop's default audio input/output, whereas
audio/alsa-loopback-automated is intended for IoT projects or projects with no internal speakers/microphone, requiring connecting a loopback cable between the line-in and line-out ports.

Add info about purpose of automated sound recording jobs (infra)

---

tools/release/README.md

The release documentation is significantly out of date. This updates it to the latest revision.
Fixes: CHECKBOX-1499
N/A
N/A

Update the release documentation (infra)

---

checkbox-snap/series_classic24/snap/snapcraft.yaml
checkbox-snap/series_uc24/snap/snapcraft.yaml

This doesn't allow us to promote any frontend to stable and it is no longer needed.
Partially part of: https://warthogs.atlassian.net/browse/CHECKBOX-1504
N/A
N/A

Turn frontend snaps into stable snaps (infra)

---

checkbox-support/debian/control

Hopefully the last PR to fix the debian package dependencies related to the USB tests change

Fix systemd debian package (BugFix)

---

contrib/pc-sanity/bin/get-image-url.sh
contrib/pc-sanity/units/pc-sanity/pc-sanity-misc.pxu
contrib/pc-sanity/units/pc-sanity/pc-sanity.pxu

- Create a new test job, to convert the [DCD](https://wiki.ubuntu.com/FoundationsTeam/Specs/OemTrackingId (DCD String)) into url, provide as a test result in submission. 
- Naming convention:
- canonical-oem-{project}-{series}-{kernel track}-{build-stamp}
- `https://oem-share.canonical.com/partners/{project}/share/releases/{series}/{kernel track}/{build-stamp}/`
Resolves: https://warthogs.atlassian.net/browse/OEX86-346
None that I'm aware of
- Run `get-image-url.sh` on somerville/stella with hwe/oem-24.04/oem-24.04-proposed kernels
- Run `checkbox-cli run job 'com.canonical.certification::info/url-from-dcd'`
`===========================[ Running Selected Jobs ]============================
==============[ Running job 1 / 1. Estimated time left: 0:00:00 ]===============
----[ Provides image …

Add image-url test job and get-image-url.sh script (New)

---

contrib/pc-sanity/units/pc-sanity/pc-sanity.pxu

Fix unexpected non-empty line in pc-sanity-base's _description
unexpected non-empty line will make pc-sanity fail to build

Fix Unexpected non-empty line (BugFix)

---

.github/workflows/checkbox-promote-beta-to-candidate.yml
.github/workflows/checkbox-promote-beta-to-candidate/job.template

Include new configuartions and update debian install command
N/A
N/A
Ran to completion,

Expand matrix of promo job (infra)

---

contrib/checkbox-ce-oem/checkbox-provider-ce-oem/units/video-codec/jobs.pxu

The length of [template-summary](https://github.com/canonical/checkbox/commit/ae8401ceefa7d62f52c4d768f3741a5fba2b960c#diff-9adb9822e811772774b0a33f77795d9cf9a903fba73e664990e2f4d024e37439R37) is over 80 characters, we cannot build the Checkbox.
Therefore, I reduce the size of it.

Reduce the length of template-summary (BugFix)

---

providers/base/bin/cpuid.py

This PR simply fixes that case in the `0x906a3` CPU ID.
No issue was created for this bug
No documentation needed
No additional tests needed

Fix case typo in 0x906a3 CPU ID (Bugfix)

---

docs/community/support.rst

In order to get support, Checkbox users can go to the dedicated section on the Ubuntu Discourse. The "Getting support" page is updated to reflect this.
Tested locally using `make run` from the `docs/` directory.

Add link to Ubuntu Discourse section in docs (infra)

---

contrib/checkbox-ce-oem/checkbox-provider-ce-oem/bin/gadget_interface_utils.py

fix black format issue
fix black format issue
N/A
N/A

fix black format issue (Bugfix)

---

providers/sru/units/sru.pxu

Remove stress/cpu_stress_ng_test from SRU (Bugfix)

---

providers/certification-client/units/client-cert-odm-desktop-18-04.pxu
providers/certification-client/units/client-cert-odm-desktop-20-04.pxu
providers/certification-client/units/client-cert-odm-desktop-22-04.pxu
providers/certification-client/units/client-cert-odm-desktop-24-04.pxu

`suspend-key-led-oops-check-cert` is manual test plan and shouldn't be added in the automated test.
#1457

Removing manual `suspend-key-led-oops-check-cert` test plan in odm automated test (BugFix)

---

.github/workflows/dispatch_lab_job.yaml

I need this to land to conduct testing as the `gh` tool doesnt seem to support dispatching the event I need

Empty implementation of the comment action (infra)

---

providers/base/units/stress/test-plan.pxu

There is no more hibernate test requirement in the iot project and `stress-full` test plan is only included in the iot related test plans. Therefore, removing this test from stress-full test plan won't impact other fields.
#1382

Remove hibernate from iot test plan (BugFix)

---

providers/base/bin/cpuid.py

New cpuid for turin as per issue
Fix: https://github.com/canonical/checkbox/issues/1513
N/A
N/A

Add cpuid for turin (bugfix)

---

providers/base/units/dock/jobs.pxu

The user of test case id: thunderbolt/storage-manual is root, however id: dock/all-init-thunderbolt3-storage-manual is normal user.
This PR set the user to root for  `id: dock/all-init-thunderbolt3-storage-manual`
#1545 
submission: https://certification.canonical.com/hardware/202407-34191/submission/400085/test-results/pass/

fix dock/all-init-thunderbolt3-storage-manual is not set user to root (Bugfix)

---

checkbox-support/debian/control

Added v4l-utils dependency for future test cases to have access to `v4l2-compliance` and `v4l2-ctl`.
Verified on ubuntu16, 18, 20 virtual machines and ubuntu 22, 24 real machines that `sudo apt install v4l-utils` works and includes the above commands

Add v4l-utils dependency (New)

---

.github/ISSUE_TEMPLATE/bug_report.yaml
.github/workflows/label-cert-blocker-issue.yaml

Add a checkbox (no pun intended) in the issue template so that reporter can mention whether or not this is about a cert-blocker test case.
Add a GitHub Action to automatically label the issue if this is checked.

Automatically label issues affecting cert-blocker jobs (infra)

---

.github/workflows/label-cert-blocker-issue.yaml

The issue template outputs a different string than expected.
Modifying the workflow to match this.

Fix auto-label cert-blocker issue workflow (infra)

---

.github/ISSUE_TEMPLATE/bug_report.yaml
.github/workflows/label-cert-blocker-issue.yaml

Use "description" field for checkbox in issue template, and update workflow to use this.
This is to make it easier on the reporter, and on the workflow to automatically label new issues

Change label and description for new checkbox (infra)

---

checkbox-support/checkbox_support/helpers/retry.py

- Retry functions from `checkbox-support` print to STDOUT, but the output is out of order.
- Flushes STDOUT to ensure the print messages get through in order with STDERR messages that the scripts may be using.

Flush stdout in retry functions (BugFix)

---

providers/base/bin/cpuid.py
providers/base/tests/test_cpuid.py

Added the cpuid to detect the Hygon C86-4G 7490 CPU 
Unit tests were also added
https://github.com/canonical/checkbox/issues/1603

Added the cpuid to detect the Hygon C86-4G 7490 CPU (Bugfix)

---

contrib/pc-sanity/bin/check-production-suite.sh
contrib/pc-sanity/units/pc-sanity/pc-sanity-check-env.pxu

Run check-production-suite for 24.04 and later versions.
Include stella and sutton in 24.04

pc-sanity: Update platform archive checks test for 24.04 (BugFix)

---

.github/ISSUE_TEMPLATE/bug_report.yaml

Add two fields:
- Expected Result
- Actual Result
to make sure we better understand the expectations from the bug author.

Update issue template (infra)

---

contrib/pc-sanity/bin/get-oem-info.sh

Can get oem code name "sutton" successfully on noble release.
False alarm on [JIRA/SUTTON-517](https://warthogs.atlassian.net/browse/SUTTON-517).
Test on several DUTs.

Fix pc-sanity/platform_meta_test for sutton 24.04 (bugfix)

---

checkbox-core-snap/README.md

Fix order of commands in the debug section.

Update snapcraft build README.md (infra)

---

contrib/checkbox-ce-oem/checkbox-ce-oem-snap/series_classic24/snap/snapcraft.yaml
contrib/checkbox-ce-oem/checkbox-ce-oem-snap/series_uc20/snap/snapcraft.yaml
contrib/checkbox-ce-oem/checkbox-ce-oem-snap/series_uc22/snap/snapcraft.yaml
contrib/checkbox-ce-oem/checkbox-ce-oem-snap/series_uc24/snap/snapcraft.yaml

Since maybe in the future, we will need to run the docker test via checkbox-ce-oem on core image, we have to define plugs to connect.
Besides, I completed the `TODO` for series 24 that I added back checkbox24 for build snaps and default providers.
According to #1285, we should have rename from plainbox to checkbox for checkbox snap, hence, there should be no exception for checkbox-ce-oem.
N/A
N/A
I have checked that it is buildable and there is docker tests.

[checkbox-ce-oem] Add interface for docker provider for uc and checkbox24 for series 24 building (Bugfix)

---

contrib/checkbox-ce-oem/checkbox-provider-ce-oem/units/power-management/manifest.pxu

Modify description of manifest that used by pdu cold reboot test to more sepcific to the platform that not supported RTC wake and intend to power cycle via PDU.

Modify description of manifest that used by pdu cold reboot test (Bugfix)

---

contrib/checkbox-ce-oem/checkbox-provider-ce-oem/units/optee/jobs.pxu

print out the description of optee test case on the console
N/A
N/A
N/A

add optee test description into console output (Bugfix)

---

providers/gpgpu/units/jobs.pxu
providers/gpgpu/units/test-plan.pxu

- This PR adds blocker / non-blocker status to the test plans.
- This PR also explicitly defines the `bootstrap_include` section for the test plans

Add blocker and bootstrap include to GPGPU jobs (New)

---

contrib/checkbox-ce-oem/checkbox-provider-ce-oem/units/gadget/jobs.pxu

corrected the manifest for gadget testing
Corrected the manifest for the gadget plug and slot verification test
None
None
https://certification.canonical.com/hardware/202406-34081/submission/409158/

corrected the manifest for gadget testing (Bugfix)

---

.github/workflows/pr_validation.yaml

Update apt repo (infra)

---

.github/workflows/deb_validator.yaml
.github/workflows/metabox.yaml
checkbox-ng/tox.ini
checkbox-support/tox.ini
contrib/checkbox-ce-oem/checkbox-provider-ce-oem/tox.ini
metabox/configs/local-source-24.04.py
metabox/configs/remote-source-24.04.py
metabox/metabox/core/lxd_execute.py
metabox/metabox/core/machine.py
providers/base/tox.ini
providers/certification-client/tox.ini
providers/certification-server/tox.ini
providers/docker/tox.ini
providers/genio/tox.ini
providers/gpgpu/tox.ini
providers/iiotg/tox.ini
providers/resource/tox.ini
providers/sru/tox.ini
providers/tpm2/tox.ini
providers/tutorial/tox.ini
tools/release/tox.ini

We have to start testing checkbox for noble, so python 3.12 and metabox testing on noble. This updates all tox and metabox workflow
Fixes: CER-2857
N/A
N/A
to verify this, beside the pipeline, check that all the packages are at the same version in the tox jobs

Noble testing infra (infra)

---

providers/base/bin/cpuid.py

Add additional ARL CPUID string
#1752
CHECKBOX-1767
NA
NA (only adds an additional string to an existing list)

bin/cpuid.py add additional ARL CPUID string resolves #1752 (New)

---

.github/workflows/checkbox-ce-oem-daily-build.yml
.github/workflows/checkbox-ce-oem-edge-builds.yml
.github/workflows/checkbox-daily-cross-builds.yaml
.github/workflows/checkbox-daily-native-builds.yaml
.github/workflows/daily-builds.yml
.github/workflows/deb-daily-builds.yml

Github documentation is fantastic
This is not only not needed, it breaks the workflow because the name is reserved
N/A
N/A
Ran the action and cancelled it to aoid store upload https://github.com/canonical/checkbox/actions/runs/13717123524

Fix gh token passing (infra)

---

.github/actions/checkbox_source_deb/action.yaml
.github/workflows/dispatch_lab_job.yaml
tools/lab_dispatch/generic_source.yaml

There's no need to interact with that scriptlet anymore.
N/A
Up to date.
The workflow itself.

Remove scriplet from GH action (Infra)

---

.github/workflows/checkbox-ce-oem-edge-builds.yml

Push uc24 to the latest/edge channel instead of classic24.
N/A
N/A
N/A

Push uc24 to the latest/edge channel (Infra)

---

contrib/pc-sanity/units/pc-sanity/pc-sanity-thermal.pxu

Add Lunar Lake's thermal devices ID
refer https://kernel.ubuntu.com/forgejo/kernel/noble-linux-oem/commit/79b510c49207489f7e019b4c397b04d22b4dfd8d

Add Lunar Lake ID for thermal test (Bugfix)

---

providers/base/units/stress/boot.pxu

We found the command to put system into power off in cold boot stress test is different with one time cold boot that under power-management category.
I've tried with one of my X86 machine
https://certification.canonical.com/hardware/202502-36310/submission/418319/test-results/pass/?term=cold-boot-loop
and arm64
https://certification.canonical.com/hardware/202501-36214/submission/418392/test-results/pass/

Unify the cold boot stress method with onetime cold boot (BugFix)

---

checkbox-support/checkbox_support/tests/test_run_watcher.py

There was a subprocess call that was not properly mocked on the unit tests, making the tests hang on 18.04 builds
https://code.launchpad.net/~checkbox-dev/+archive/ubuntu/edge/+build/30612641

Patched missing Popen (BugFix)

---

.github/workflows/checkbox-daily-cross-builds.yaml
.github/workflows/deb_validator.yaml
.github/workflows/metabox.yaml
.github/workflows/tox-checkbox-ng.yaml
.github/workflows/tox-checkbox-support.yaml
.github/workflows/tox-contrib-provider-ce-oem.yaml
.github/workflows/tox-provider-base.yaml
.github/workflows/tox-provider-certification-client.yaml
.github/workflows/tox-provider-certification-server.yaml
.github/workflows/tox-provider-docker.yaml
.github/workflows/tox-provider-genio.yaml
.github/workflows/tox-provider-gpgpu.yaml
.github/workflows/tox-provider-iiotg.yaml
.github/workflows/tox-provider-resource.yaml
.github/workflows/tox-provider-sru.yaml
.github/workflows/tox-provider-tpm2.yaml
.github/workflows/tox-provider-tutorial.yaml

ubuntu-20.04 is going away, this is our internal replacement while we still need it
Fixes: CHECKBOX-1821
N/A
N/A

Migrate ubuntu-20.04 to self-hosted focal (infra)

---

.github/workflows/checkbox-daily-cross-builds.yaml

- Fixes some problems introduced by #1851

Fix daily builds workflow syntax (BugFix)

---

.github/workflows/checkbox-ce-oem-daily-builds.yaml
.github/workflows/checkbox-ce-oem-daily-cross-builds.yaml
.github/workflows/checkbox-ce-oem-daily-native-builds.yaml
contrib/checkbox-ce-oem/checkbox-ce-oem-snap/prepare.sh
contrib/checkbox-ce-oem/checkbox-ce-oem-snap/series_classic20/snap/snapcraft.yaml
contrib/checkbox-ce-oem/checkbox-ce-oem-snap/series_classic22/snap/snapcraft.yaml
contrib/checkbox-ce-oem/checkbox-ce-oem-snap/series_classic24/snap/snapcraft.yaml
contrib/checkbox-ce-oem/checkbox-ce-oem-snap/series_uc20/snap/snapcraft.yaml
contrib/checkbox-ce-oem/checkbox-ce-oem-snap/series_uc22/snap/snapcraft.yaml
contrib/checkbox-ce-oem/checkbox-ce-oem-snap/series_uc24/snap/snapcraft.yaml

Refactor the whole checkbox-ce-oem build workflow to align with checkbox.
https://github.com/canonical/checkbox/actions/runs/14399122383/job/40380768638

Update checkbox-ce-oem workflow to align with checkbox (Infra)

---

contrib/checkbox-ce-oem/checkbox-provider-ce-oem/units/optee/jobs.pxu

add optee manifest to optee test cases, so we could skipped them when the system does not has OPTEE.
N/A
N/A
N/A

add optee manifest to optee test cases (Bugfix)

---

checkbox-ng/plainbox/provider_manager.py

The warning is over-issued because the default value is wrong

Default value is "*" not ["*"] (bugfix)

---

checkbox-ng/setup.cfg
checkbox-support/setup.cfg
docs/.sphinx/wordslist.txt
docs/how-to/ancient-python.rst
docs/how-to/index.rst

Iterating on Python3.5 is hard and confusing the first time one does it. I've created this new method which is pretty hands off, 1 command and you are in the environment to iterate freely.
Minor: while dogfooding this, I've discovered that ancient versions of painbox dont pull psutil because they use the setup.cfg file, which is wrong. This also fixes that.
Fixes: https://warthogs.atlassian.net/browse/CHECKBOX-1878
This is documentation
Dogfooded the how-to, just run through it and test the environment by starting Checkbox / running some tests from the manage.py

Document how to work on python3.5 (infra)

---

contrib/checkbox-ce-oem/checkbox-provider-ce-oem/bin/optee_helper.py
contrib/checkbox-ce-oem/checkbox-provider-ce-oem/bin/rpmsg_load_firmware.py
contrib/checkbox-ce-oem/checkbox-provider-ce-oem/bin/rpmsg_tests.py
contrib/checkbox-ce-oem/checkbox-provider-ce-oem/tests/test_rpmsg_load_firmware.py
contrib/checkbox-ce-oem/checkbox-provider-ce-oem/tests/test_rpmsg_tests.py

fixed scripts issues related to python systemd
Following three test scripts in checkbox-provider-ce-oem is not functional due to the python3-systemd module been removed.
- optee_helper.py
- rpmsg_load_firmware.py      
- rpmsg_tests.py
Insteads of retrieve journal logs via python3-systemd package, uses the subprocess to call journalctl directly.
https://github.com/canonical/checkbox/issues/1889
N/A
N/A

fixed test scripts in checkbox-ce-oem related to python3 systemd (Bugfix)

---

.github/workflows/checkbox-stable-release.yml

Fixed core24 promo
Fixes: https://warthogs.atlassian.net/browse/CHECKBOX-1892
N/A
N/A

Clearly wrong promotion fixed (infra)

---

providers/base/units/suspend/test-plan.pxu

Some vendors such as Dell do not use the power LED to indicate suspend mode anymore, especially when using s2idle. As such, and because LEDs are usually handled at firmware or embedded controller level, the cert-blocker status is removed from this job to prevent blocking the certificate issuing.
Fix CHECKBOX-1746

Remove cert-blocker status from led/power-blink-suspend (bugfix)

---

contrib/checkbox-ce-oem/checkbox-provider-ce-oem/bin/multiple-otg.sh

On carmel device, the original script cannot find the correct UDC for the USB port.
Hence updated the script to look for `of_node` in the under `$device_path/*/$udc` 
Below is the USB node and UDC link on carmel device:
```
ubuntu@ubuntu:/sys/devices/platform/soc@0/a600000.usb$ ll
total 0
drwxr-xr-x   7 root root    0 Jun 23 01:51 ./
drwxr-xr-x 236 root root    0 Jun 23 01:50 ../
lrwxrwxrwx   1 root root    0 Jun 23 01:51 consumer:typec:port0 -> ../../../virtual/devlink/platform:a600000.usb--typec:port0/
lrwxrwxrwx   1 root root    0 Jun  4 12:24 driver -> ../../../../bus/platform/drivers/dwc3-qcom/
-rw-r--r--   1 root root 4096 Jun 23 01:51 driver_override
drwxr-xr-x   3 root root    0 Jun 23 01:51 gadget.1/
lrwxrwxrwx   1 root root    0 Jun 23 01:51 iommu -> …
```

update ce-oem otg test script to read udc of usb node on carmel device (new)

---

providers/base/units/suspend/suspend-graphics.pxu
providers/base/units/suspend/suspend.pxu

This PR introduces the "before" field for the *resolution_before_suspend* tests to ensure they are run before suspend.
https://warthogs.atlassian.net/browse/CHECKBOX-1626
The test has been run on some devices that were failing these tests before due to incorrect ordering:
- https://certification.canonical.com/hardware/202008-28109/submission/434002/
- https://certification.canonical.com/hardware/202005-27942/submission/434004/
- https://certification.canonical.com/hardware/202106-29206/submission/434003/

Updated before-suspend jobs to include the "before" flag (bugfix)

---

.github/workflows/dispatch_lab_job.yaml

Use commit from the change in the way checkbox-ng is installed so that the action works as expected, and does not fail with the
pipx: error: unrecognized arguments: --spec checkbox-ng
error.

Fix commit id in dispatch lab job action (infra)

---

providers/base/bin/cpuid.py

Adds a CPUID for AMD Grado. 
CPU: AMD EPYC 4545P 16-Core Processor
Reference for CPUID can be found in the following certificate:  https://certification.canonical.com/hardware/202504-36672/submission/436028
Resolves #1994 
Resolves [CHECKBOX-1967](https://warthogs.atlassian.net/browse/CHECKBOX-1967)
[CHECKBOX-1967]: https://warthogs.atlassian.net/browse/CHECKBOX-1967?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add AMD Grado CPUID (Bugfix)

---

docs/conf.py

Update Sphinx configuration to ignore link check on the GNU license URL, which caused rate limiting:
```
-rate limited-   https://www.gnu.org/licenses/gpl-3.0.html | sleeping...
```
NA
NA
Link check on PR succeeds.

Docs: ignore link check on GNU license (Infra)

---

providers/base/bin/wifi_nmcli_test.py

I fix a typo in the script.
N/A
N/A
N/A

Fix typo from mmcli to nmcli (Bugfix)

---

checkbox-core-snap/series18/snap/snapcraft.yaml
checkbox-core-snap/series20/snap/snapcraft.yaml
checkbox-core-snap/series22/snap/snapcraft.yaml
checkbox-core-snap/series24/snap/snapcraft.yaml

This new version contains a fix that might help with the problem described in #1628.

Update FWTS to V25.07.00 for series18~24 snaps (infra)

---

providers/base/units/dock/jobs.pxu
providers/base/units/dock/manifest.pxu
providers/base/units/dock/test-plan.pxu

This PR refactors the dock test to make it easier and provides wilder coverage.
1. separate manifest from non dock test plans to ensure the manifest won't mislead
2. add new `init-connection` test case as the root dependency for all jobs to ensure the real init connection test is executed.
3. add new test sets `suspend-hotplug` to ensure dock could work after hotplug under suspend.
4.  add new `all-*-ethernet-detect` as dependency of `all-*-networking-gateway-ping` and `all-*-networking-ntp` to archive the manifest separating.
5. add `certification-status=blocker` to all test cases
6. modify wording to make the description and verification more clear. 
https://warthogs.atlassian.net/browse/OEMQA-6118
https://certification.canonical.com/hardware/202503-36528/submission/441901/

refactor docking test (Bugfix)

---

contrib/checkbox-ce-oem/checkbox-provider-ce-oem/bin/nvidia_drm_modeset_check.py
contrib/checkbox-ce-oem/checkbox-provider-ce-oem/units/graphics/jobs.pxu
contrib/checkbox-ce-oem/checkbox-provider-ce-oem/units/graphics/manifest.pxu
contrib/checkbox-ce-oem/checkbox-provider-ce-oem/units/graphics/test-plan.pxu

add a test case to ensure Nvidia proprietary driver and DRM modeset are enabled for proper rendering
side-loaded test result
```
ubuntu@ubuntu:~$ checkbox-ce-oem.checkbox-cli run com.canonical.contrib::ce-oem-graphics-automated
$PROVIDERPATH is defined, so following provider sources are ignored ['/snap/checkbox-ce-oem/3141/providers/checkbox-provider-ce-oem', '/home/ubuntu/.local/share/plainbox-providers-1', '/var/tmp/checkbox-providers-develop'] 
Using sideloaded provider: checkbox-provider-ce-oem, version 0.1 from /var/tmp/checkbox-providers/checkbox-provider-ce-oem
Skipped file: /var/tmp/checkbox-providers/checkbox-provider-ce-oem/bin/gst_utils.py
=========================[ Running Selected Test Plan ]=========================
=========[ Running job 1 / 1. Estimated time left (at …
```

add nvidia drm modeset check (New)

---

contrib/checkbox-ce-oem/checkbox-provider-ce-oem/units/test-plan-ce-oem.pxu

add nvidia-drm test plan into 
list-bootstrapped results with side-loaded checkbox-provider-ce-oem
```
ceqa@test-1234:~$ checkbox-ce-oem.checkbox-cli list-bootstrapped com.canonical.contrib::ce-oem-iot-server-24-04-automated
Using sideloaded provider: checkbox-provider-ce-oem, version 0.1 from /var/tmp/checkbox-providers/checkbox-provider-ce-oem
Skipped file: /var/tmp/checkbox-providers/checkbox-provider-ce-oem/bin/gst_utils.py
Using sideloaded provider: checkbox-provider-ce-oem, version 0.1 from /var/tmp/checkbox-providers/checkbox-provider-ce-oem
com.canonical.plainbox::manifest
com.canonical.certification::executable
com.canonical.certification::interface
com.canonical.certification::connections
com.canonical.certification::model_assertion
com.canonical.certification::serial_assertion …
```

add nvidia-drm test plan (New)

---

providers/base/units/keys/jobs.pxu
providers/base/units/power-management/jobs.pxu

The following jobs now depend on suspend_advanced_auto, so they will be 
scheduled to run only after the suspend advanced auto job finishes:
- keys/power-button-suspend
- power-management/suspend-on-battery-power
- power-management/suspend-on-AC-power
https://certification.canonical.com/hardware/202506-36804/submission/453217/

Add jobs dependency with suspend_advanced_auto (BugFix)

---

providers/base/units/stress/test-plan.pxu

Replace `disk/disk_stress_ng_.*` with `disk/disk_stress_ng_name`. 
Since the new test `disk/disk_stress_ng_sru` was added a few weeks ago, using `disk/disk_stress_ng_.*` results in duplicate jobs during our testing. 
Hence updated it to use template_id for better mapping.
N/A
N/A
list-bootstrapped
before change:
```
com.canonical.certification::disk/disk_stress_ng_sda
com.canonical.certification::disk/disk_stress_ng_sdb
com.canonical.certification::disk/disk_stress_ng_sdc
com.canonical.certification::disk/disk_stress_ng_sdd
com.canonical.certification::disk/disk_stress_ng_sde
com.canonical.certification::disk/disk_stress_ng_sdf
com.canonical.certification::disk/disk_stress_ng_sdg
com.canonical.certification::disk/disk_stress_ng_sdh
com.canonical.certification::disk/disk_stress_ng_sru_sda …
```

Use template-id to include disk_stress_ng in stress-ng-automated test plan (BugFix)
